// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    cookieSecret: 'myBlog',
    db: 'my_blog3',
    url: 'mongodb://localhost/my_blog3'
  };

}).call(this);

//# sourceMappingURL=settings.map
